name: appoint
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  charts_flutter: ^0.9.0
  wakelock: ^0.1.4+1
  camera: 0.7.0+4
  frideos: ^0.1.0
  eva_icons_flutter: ^3.0.0
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  numberpicker: ^2.1.1
  path_provider: ^1.6.24
  provider: ^5.0.0
  screenshot: ^1.2.1
  share_plus: ^1.2.0
  flutter_spinkit: ^4.1.2+1
  dio: 1.0.0
  google_fonts: ^1.1.2
  url_launcher: ^5.7.1
  flutter_svg: ^0.19.3
  flutter_riverpod: ^0.11.1
  styled_widget: ^0.2.1+2
  responsive_framework: ^0.0.4
  # assets_audio_player: ^2.0.15
  tinycolor: ^1.0.2
  copy_with_extension: ^1.2.0
  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.0+1
  flutter_icons: ^1.1.0
  flutter_tabler_icons: ^1.0.2
  cloud_firestore: ^0.16.0
  
  cool_alert: ^1.0.3
  google_nav_bar: ^5.0.2
  font_awesome_flutter: ^8.12.0
  carousel_slider: ^3.0.0
  typicons_flutter: ^0.4.2
  quick_actions: ^0.5.0
  introduction_screen: ^2.0.0
  webview_flutter: ^1.0.7
  device_apps: ^1.3.0
  android_intent: ^0.3.7+7
  # flutter_html: ^1.0.0
  # http: ^0.12.2
  flutter_localizations:
    sdk: flutter
  intl_translation: ^0.17.10+1
dependency_overrides:
   intl: ^0.17.0-nullsafety.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.2
  copy_with_extension_gen: ">=1.0.0 <2.0.0"
  flutter_launcher_icons: ^0.7.3
# dev_dependencies:
#   flutter_test:
#     sdk: flutter
#   intl_translation: ^0.17.10+1
# dependency_overrides:
#    intl: ^0.17.0-nullsafety.2
# dev_dependencies:
#   flutter_test:
#     sdk: flutter
#   build_runner: ^1.10.2
#   copy_with_extension_gen: ">=1.0.0 <2.0.0"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/asset/audio/gong.mp3
    - assets/asset/images/
    - assets/meditation.png
    - assets/reminder.png
    - assets/call.png
  # asset:
  #   - asset/audio/
  #   - asset/images/
    
flutter_intl:
  enabled: true
    # - assets/icon
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icon.png"